name: Fork Maintenance

on:
  schedule:
    - cron: '23 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  fork-maintenance:
    name: Fork Maintenance
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - name: Install komac
        uses: UnownPlain/install-komac@main

      - name: Sync Fork & Cleanup Branches
        env:
          KOMAC_FORK_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
        run: |
          komac sync
          komac cleanup -a
