name: Lint Project

on:
  push:
    branches:
      - main
    paths-ignore:
      - version_state/**
  pull_request:
  workflow_dispatch:

jobs:
  lint-project:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
      - name: Install Dependencies
        run: bun ci
      - name: Check Formatting
        run: bun format --check
      - name: Lint & Type check
        run: bun lint --deny-warnings
