name: Update Packages

on:
  schedule:
    - cron: '7 * * * *'
    - cron: '17 * * * *'
    - cron: '28 * * * *'
    - cron: '37 * * * *'
    - cron: '49 * * * *'
    - cron: '58 * * * *'
  workflow_dispatch:

jobs:
  update-packages:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
      - name: Install Dependencies
        run: bun ci --production
      - name: Install komac
        uses: UnownPlain/install-komac@main
        with:
          version: nightly
      - name: Update Packages
        env:
          KOMAC_FORK_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
        run: bun start
