name: Update Packages

on:
  schedule:
    - cron: '7 * * * *'
    - cron: '17 * * * *'
    - cron: '28 * * * *'
    - cron: '37 * * * *'
    - cron: '49 * * * *'
    - cron: '58 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  update-packages:
    name: Update Packages
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
        with:
          no-cache: true

      - name: Install Dependencies
        run: bun ci --production

      - name: Update Packages
        env:
          KOMAC_FORK_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
        run: bun start
